In [127]:
import pandas as pd

In [128]:
# import csv file

df = pd.read_csv(r"C:\Users\lenovo\Downloads\Amazon_laptops.csv")
df

,title,price,rating,brand,ram,storage,color,processor
0,"HP 15 (i5 14th Gen), Intel Core 5, 16GB RAM (U...","75,990",3.6,HP,16GB,512GB,Silver,Intel
1,"HP Omnibook 3, Snapdragon X Processor 45 Tops ...","69,990",3.2,HP,16GB,512GB,Silver,Snapdragon
2,Lenovo V15 G4 AMD Athlon Silver 7120U Laptop 8...,"44,999",4.0,Lenovo,8GB,512GB,Silver,AMD
3,"ASUS Vivobook 16,Smartchoice, 13th Gen, Intel ...","67,990",4.0,ASUS,16GB,512GB,Silver,Intel
4,Apple 2026 MacBook Neo 13″ Laptop with A18 Pro...,"73,990",4.8,Apple,8GB,256GB,Indigo,NaN
...,...,...,...,...,...,...,...,...
552,Apple 2026 MacBook Air 13″ Laptop with M5 chip...,"1,72,490",4.7,Apple,16GB,1TB,NaN,NaN
553,Apple 2026 MacBook Neo 13″ Laptop with A18 Pro...,"73,990",4.8,Apple,8GB,256GB,Indigo,NaN
554,Apple 2026 MacBook Neo 13″ Laptop with A18 Pro...,"73,990",4.7,Apple,8GB,256GB,Silver,NaN
555,"Dell 15 AI Powered Laptop, Intel Core Ultra 5 ...","81,490",5.0,Dell,16GB,NaN,NaN,Intel
556,Apple 2026 MacBook Air 15″ Laptop with M5 chip...,"2,00,490",4.7,Apple,16GB,1TB,Silver,NaN

In [129]:
# 1. convert title in correct form

df.columns = df.columns.str.strip().str.title()
df.columns

Index(['Title', 'Price', 'Rating', 'Brand', 'Ram', 'Storage', 'Color',
       'Processor'],
      dtype='object')

In [130]:
# 2. see the first 5 rows
df.head()

,Title,Price,Rating,Brand,Ram,Storage,Color,Processor
0,"HP 15 (i5 14th Gen), Intel Core 5, 16GB RAM (U...","75,990",3.6,HP,16GB,512GB,Silver,Intel
1,"HP Omnibook 3, Snapdragon X Processor 45 Tops ...","69,990",3.2,HP,16GB,512GB,Silver,Snapdragon
2,Lenovo V15 G4 AMD Athlon Silver 7120U Laptop 8...,"44,999",4.0,Lenovo,8GB,512GB,Silver,AMD
3,"ASUS Vivobook 16,Smartchoice, 13th Gen, Intel ...","67,990",4.0,ASUS,16GB,512GB,Silver,Intel
4,Apple 2026 MacBook Neo 13″ Laptop with A18 Pro...,"73,990",4.8,Apple,8GB,256GB,Indigo,NaN

In [131]:
# 3.check the basic information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 557 entries, 0 to 556
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Title      557 non-null    object
 1   Price      552 non-null    object
 2   Rating     501 non-null    float64
 3   Brand      557 non-null    object
 4   Ram        527 non-null    object
 5   Storage    510 non-null    object
 6   Color      480 non-null    object
 7   Processor  388 non-null    object
dtypes: float64(1), object(7)
memory usage: 34.9+ KB

In [132]:
# 4. check duplicate value
df.duplicated().sum()

np.int64(268)

In [133]:
# 5.remove duplicate row
df = df.drop_duplicates()
df.duplicated().sum()

np.int64(0)

In [134]:
# 6. check missing values
df.isnull().sum()

Title         0
Price         5
Rating       47
Brand         0
Ram          25
Storage      33
Color        39
Processor    37
dtype: int64

In [135]:
# 8. remove extra spaces from text names
for col in df.select_dtypes(include="object"):
    df[col]=df[col].str.strip()

df[col]

C:\Users\lenovo\AppData\Local\Temp\ipykernel_12916\948622548.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col]=df[col].str.strip()

0           Intel
1      Snapdragon
2             AMD
3           Intel
4             NaN
          ...
472         Intel
477           NaN
505           NaN
525           NaN
552           NaN
Name: Processor, Length: 289, dtype: object

In [137]:
for col in df.select_dtypes(include="object"):
    df[col]=df[col].fillna("Unknown")

df[col]

C:\Users\lenovo\AppData\Local\Temp\ipykernel_12916\112575887.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col]=df[col].fillna("Unknown")

0           Intel
1      Snapdragon
2             AMD
3           Intel
4         Unknown
          ...
472         Intel
477       Unknown
505       Unknown
525       Unknown
552       Unknown
Name: Processor, Length: 289, dtype: object

In [138]:
# final check
print(df.info())
print()
print(df.isnull().sum())
print()
print(df.duplicated().sum())

<class 'pandas.core.frame.DataFrame'>
Index: 289 entries, 0 to 552
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Title      289 non-null    object
 1   Price      289 non-null    object
 2   Rating     242 non-null    float64
 3   Brand      289 non-null    object
 4   Ram        289 non-null    object
 5   Storage    289 non-null    object
 6   Color      289 non-null    object
 7   Processor  289 non-null    object
dtypes: float64(1), object(7)
memory usage: 20.3+ KB
None

Title         0
Price         0
Rating       47
Brand         0
Ram           0
Storage       0
Color         0
Processor     0
dtype: int64

0

In [139]:
df.shape

(289, 8)

In [140]:
missing_percentage = (df.isnull().sum() / len(df)) * 100

print(missing_percentage)

Title         0.000000
Price         0.000000
Rating       16.262976
Brand         0.000000
Ram           0.000000
Storage       0.000000
Color         0.000000
Processor     0.000000
dtype: float64

In [141]:
df['Price']=df['Price'].fillna( df['Price'].median())
df['Price']

TypeError: Cannot convert ['75,990' '69,990' '44,999' '67,990' '73,990' '49,990' '65,990' '69,990'
 '73,990' '62,490' '42,990' '44,990' '35,690' '35,990' '57,490' '38,700'
 '29,990' '50,500' '82,654' '44,990' '69,790' '3,42,490' '47,990' '49,450'
 '28,990' '64,390' '95,990' '1,94,990' '2,00,490' '44,990' '69,999'
 '54,990' '58,800' '60,250' '56,900' '54,058' '55,990' '82,990' '58,990'
 '32,990' '67,400' '68,990' '37,400' '24,990' '85,990' '68,490' '85,990'
 '25,640' '42,999' '87,990' '39,890' '84,990' '67,999' '68,698' '56,690'
 '48,990' '45,990' '98,990' '31,990' '77,990' '1,29,990' '65,990' '62,500'
 '84,990' '63,990' '49,990' '66,690' '1,32,990' '54,990' '70,990' '61,200'
 '66,798' '79,579.' '48,990' '82,880' '42,032' '42,999' '2,49,990'
 '79,990' '84,990' '24,900' '63,990' '1,84,990' '91,700' '57,250' '85,890'
 '84,990' '59,990' '59,800' '1,49,990' '4,82,490' '68,480' '99,990'
 '43,950' '54,650' '50,031' '3,42,490' '89,990' '1,36,990' '1,86,990'
 '2,34,454' '57,990' 'Unknown' '1,69,890' '85,000' '62,350' '53,280'
 '81,490' '68,700' '3,19,990' '1,56,555' '1,54,700' '63,990' '82,990'
 '73,490' '49,400' '58,990' '59,990' '1,26,790' '52,999' '55,780'
 '3,34,990' '2,90,000' '5,31,490' '68,990' '1,42,990' '2,69,990' '75,990'
 '69,990' '4,64,490' '44,990' '1,76,990' '1,94,990' '1,55,990' 'Unknown'
 '78,100' '5,13,990' '52,990' '81,700' '81,990' '93,990' '27,000'
 '2,31,490' '2,00,490' '1,24,990' '61,500' '26,000' '2,00,042' '69,900'
 '48,999' '55,100' '62,500' '2,55,990' '71,990' '1,70,999' '57,880'
 '54,891' '1,85,490' '68,480' '69,990' '53,999' '45,999' '26,000' '72,365'
 '68,390' '44,680' '1,82,990' '94,990' '1,75,000' '59,990' '70,849'
 '51,990' '1,59,990' '2,39,990' '91,289' '59,950' '46,590' '2,22,990'
 '54,680' '1,48,000' '1,36,990' '2,19,990' '49,560' '1,74,990' '49,999'
 '55,990' '1,62,990' '1,05,540' '52,990' '47,999' 'Unknown' '48,990'
 '73,990' '63,425' '74,990' '66,929' '58,990' '58,700' '79,990' '85,000'
 '59,990' '2,09,780' '54,500' '1,58,990' '62,850' '1,39,990' '69,990'
 '67,990' '83,490' '62,990' '99,990' '78,000' '79,990' '69,999' '55,100'
 '69,990' '58,990' '89,900' '72,900' '60,990' '1,34,990' '72,900' '60,999'
 'Unknown' '94,900' '52,680' '86,990' '56,999' '1,03,990' '2,49,990'
 '1,93,990' '82,990' '2,15,990' '94,990' '1,14,990' '4,45,000' '5,89,990'
 '1,74,500' '4,31,990' '1,18,990' '94,990' '1,99,990' '9,99,990' '31,900'
 '58,990' '63,990' '1,36,990' '5,29,990' '60,990' '53,780' '88,990'
 '1,86,990' '1,05,000' '19,990' '61,490' '48,990' '2,73,490' '91,990'
 '3,49,990' '50,999' '98,800' '58,600' '84,140' '51,100' '28,299' '50,490'
 '44,999' '53,200' '1,01,990' '69,999' '65,990' '9,999' '56,000'
 '1,03,990' '82,970' '44,604' '53,990' '1,76,990' 'Unknown' '40,999'
 '83,400' '47,999' '1,15,990' '40,990' '58,990' '5,13,990' '1,72,490'
 '4,75,490' '1,72,490'] to numeric

In [107]:
# Converting from text to numeric, removing ₹.
# Converting text prices to numeric
df["Price"] = (
    df["Price"]
    .astype(str)
    .str.replace("₹", "", regex=False)
    .str.replace(",", "", regex=False)
    .str.strip()
)

df["Price"] = pd.to_numeric(df["Price"], errors="coerce")
df["Price"]

C:\Users\lenovo\AppData\Local\Temp\ipykernel_12916\3841140346.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Price"] = (
C:\Users\lenovo\AppData\Local\Temp\ipykernel_12916\3841140346.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Price"] = pd.to_numeric(df["Price"], errors="coerce")

0       75990.0
1       69990.0
2       44999.0
3       67990.0
4       73990.0
         ...
472     58990.0
477    513990.0
505    172490.0
525    475490.0
552    172490.0
Name: Price, Length: 289, dtype: float64

In [142]:
# rating

df["Rating"].dtype
df["Rating"].unique()

array([3.6, 3.2, 4. , 4.8, 3.7, 4.1, 3.8, 4.7, 4.2, 3.4, 1. , 3.9, 2.8,
       nan, 5. , 4.6, 4.3, 4.4, 3.3, 3. , 3.5, 4.5, 2.5, 3.1, 2.4, 2.9,
       2. , 2.7, 4.9, 2.6])

In [143]:
import numpy as np
df.loc[(df['Rating']<0) | (df['Rating']>5),
"Rating"] =np.nan

In [144]:
df['Rating']=df['Rating'].fillna(df['Rating'].median())

C:\Users\lenovo\AppData\Local\Temp\ipykernel_12916\1997920343.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Rating']=df['Rating'].fillna(df['Rating'].median())

In [145]:
print(df['Rating'].isnull().sum())

0

In [146]:
# clean brand
df["Brand"]=df["Brand"].str.strip().str.title()
df["Brand"]

C:\Users\lenovo\AppData\Local\Temp\ipykernel_12916\3552655982.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Brand"]=df["Brand"].str.strip().str.title()

0          Hp
1          Hp
2      Lenovo
3        Asus
4       Apple
        ...
472      Dell
477     Apple
505     Apple
525     Apple
552     Apple
Name: Brand, Length: 289, dtype: object

In [147]:
print(df["Brand"].value_counts())

Brand
Hp           85
Lenovo       73
Acer         39
Asus         26
Dell         21
Apple        18
Msi           7
Unknown       5
Alienware     5
Microsoft     2
New           2
Samsung       1
Model         1
Primebook     1
Tech          1
Maxbook       1
Jiobook       1
Name: count, dtype: int64

In [148]:
# Extract RAM number, e.g. 16GB → 16 and 1TB to 1064
ram = df["Ram"].astype(str)

df["Ram"] = ram.str.extract(r"(\d+\.?\d*)")[0].astype(float)

df.loc[ram.str.contains("TB", case=False, na=False), "Ram"] *= 1064

df["Ram"] = df["Ram"].bfill().ffill()

df["Ram"]

C:\Users\lenovo\AppData\Local\Temp\ipykernel_12916\3727239078.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Ram"] = ram.str.extract(r"(\d+\.?\d*)")[0].astype(float)
C:\Users\lenovo\AppData\Local\Temp\ipykernel_12916\3727239078.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Ram"] = df["Ram"].bfill().ffill()

0      16.0
1      16.0
2       8.0
3      16.0
4       8.0
       ...
472     8.0
477    36.0
505    16.0
525    36.0
552    16.0
Name: Ram, Length: 289, dtype: float64

In [150]:
# Extract storage number and normalize TB values to GB
Storage = df["Storage"].astype("string").str.upper().str.strip()

df["Storage"] = Storage.str.extract(r"(\d+\.?\d*)")[0].astype(float)

df.loc[Storage.str.contains("TB", case=False, na=False), "Storage"] *= 1024

df["Storage"] = df["Storage"].bfill().ffill()

df["Storage"]

C:\Users\lenovo\AppData\Local\Temp\ipykernel_12916\22724708.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Storage"] = Storage.str.extract(r"(\d+\.?\d*)")[0].astype(float)
C:\Users\lenovo\AppData\Local\Temp\ipykernel_12916\22724708.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Storage"] = df["Storage"].bfill().ffill()

0       512.0
1       512.0
2       512.0
3       512.0
4       256.0
        ...
472     512.0
477    2048.0
505    1024.0
525    2048.0
552    1024.0
Name: Storage, Length: 289, dtype: float64

In [151]:
df.to_csv("laptops_data_cleaned.csv", index=False)

In [152]:
print("Data saved successfully!")

Data saved successfully!

In [153]:
df

,Title,Price,Rating,Brand,Ram,Storage,Color,Processor
0,"HP 15 (i5 14th Gen), Intel Core 5, 16GB RAM (U...","75,990",3.6,Hp,16.0,512.0,Silver,Intel
1,"HP Omnibook 3, Snapdragon X Processor 45 Tops ...","69,990",3.2,Hp,16.0,512.0,Silver,Snapdragon
2,Lenovo V15 G4 AMD Athlon Silver 7120U Laptop 8...,"44,999",4.0,Lenovo,8.0,512.0,Silver,AMD
3,"ASUS Vivobook 16,Smartchoice, 13th Gen, Intel ...","67,990",4.0,Asus,16.0,512.0,Silver,Intel
4,Apple 2026 MacBook Neo 13″ Laptop with A18 Pro...,"73,990",4.8,Apple,8.0,256.0,Indigo,Unknown
...,...,...,...,...,...,...,...,...
472,Dell Inspiron 15 DC15250 Laptop (Intel I5-1334...,"58,990",4.0,Dell,8.0,512.0,Black,Intel
477,Apple 2026 MacBook Pro Laptop with M5 Max chip...,"5,13,990",2.4,Apple,36.0,2048.0,Silver,Unknown
505,Apple 2026 MacBook Air 13″ Laptop with M5 chip...,"1,72,490",4.7,Apple,16.0,1024.0,Blue,Unknown
525,Apple 2026 MacBook Pro Laptop with M5 Max chip...,"4,75,490",5.0,Apple,36.0,2048.0,Silver,Unknown
552,Apple 2026 MacBook Air 13″ Laptop with M5 chip...,"1,72,490",4.7,Apple,16.0,1024.0,Unknown,Unknown